version: "3.9"

services:
  web:
    build: ./web                 # build key
    ports:
      - "8080:3000"
    environment:                 # environment key
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:                     # volumes key
      - ./web:/usr/src/app
    depends_on:
      - redis
    restart: always

  rotator:
    build: ./rotator
    ports:
      - "3001:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./rotator:/usr/src/app
    depends_on:
      - redis
    restart: always

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always